version: '3.9'
services:
  postgresql:
    image: postgres
    environment:
      - POSTGRES_USER=myusername
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=mypassword
    ports:
      - 5434:5432
  coordinator:
    image: maven:latest
    ports:
      - 7271:7271
    networks:
      cloud:
        aliases:
          - co
    depends_on:
      - postgresql
    deploy:
      replicas: 3
  worker:
    image: maven:latest
    volumes:
      - storage:/tmp
    networks:
      cloud:
        aliases:
            - wo
    deploy:
      replicas: 3
networks:
  cloud:
    driver: overlay
    attachable: true
volumes:
  storage:





