version: "3.9"
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      cloud:
        aliases:
          - redis
  postgresql:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=myusername
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5434:5432"
    networks:
      cloud:
        aliases:
          - postgresql
  coordinator:
    build: /Coordinator
    image: coordinator
    container_name: coordinator
    ports:
      - "7271:7271"
    volumes:
      - type: volume
        source: storage
        target: /tmp
      - type: bind
        source: /host/.
        target: /host/.
    networks:
      cloud:
        aliases:
          - coordinator
    depends_on:
      - postgresql
  worker:
    build: /Distributed-DBMS
    image: dbms
    ports:
      - "7271:7271"
    volumes:
      - type: bind
        source: /host
        target: /host
    networks:
      cloud:
        aliases:
          - worker
    deploy:
      replicas: 10
      placement:
        ,max_replicas_per_node: 3
networks:
  cloud:
    driver: overlay
    attachable: true
volumes:
  storage: