version: "3.9"
services:
  coordinator:
    image: coordinator
    container_name: coordinator
    ports:
      - target: 7271
        published: 7271
        protocol: tcp
        mode: host
    networks:
      cloud:
        aliases:
          - coordinator
  worker:
    image: worker
    networks:
      cloud:
        aliases:
          - worker
    deploy:
      replicas: 7
      placement:
        max_replicas_per_node: 10
    depends_on:
      - coordinator
    command: mvn exec:java -Dexec.mainClass="orc.main" -Dexec.cleanupDaemonThreads=false -Dsbt.classloader.close=false

networks:
  cloud:
    driver: overlay
    attachable: true
#    external: true