version: '3.9'
services:
  postgresql:
    image: postgres
    environment:
      - POSTGRES_USER=myusername
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5434:5432"
  coordinator:
    build: /Coordinator/.
    image: dbms
    ports:
      - "7271:7271"
    networks:
      cloud:
        aliases:
          - co
    depends_on:
      - postgresql
  workerscan:
    build: /Distributed-DBMS/.
    image: dbms
    volumes:
      - storage:/tmp
    networks:
      cloud:
        aliases:
          - scan
    deploy:
      replicas: 3
  workerjoin:
    image: dbms
    volumes:
      - storage:/tmp
    networks:
      cloud:
        aliases:
          - join
    deploy:
      replicas: 3
networks:
  cloud:
    driver: overlay
    attachable: true
volumes:
  storage:





