version: "3.9"
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      cloud:
        aliases:
          - postgresql
  postgresql:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=myusername
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=mypassword
    ports:
      - 5434:5432
    networks:
      cloud:
        aliases:
          - postgresql
  coordinator:
    build: /Coordinator
    image: coordinator
    container_name: coordinator
    ports:
      - target: 7271
        published: 7271
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: storage
        target: /tmp
      - type: bind
        source: /host/.
        target: /host/.
    networks:
      cloud:
        aliases:
          - coordinator
    depends_on:
      - postgresql
  worker:
    build: /Distributed-DBMS
    image: dbms
    ports:
      - target: 7272
        published: 7272
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: /host
        target: /host
    networks:
      cloud:
        aliases:
          - worker
    deploy:
      replicas: 3
networks:
  cloud:
    driver: overlay
    attachable: true
volumes:
  storage: