version: '3.9'
services:
  coordinator:
    image: kristalys/dbms-coordinator:1.1
    container_name: coordinator
    deploy:
      placement:
        constraints:
          - "node.role==manager"
    ports:
      - target: 7271
        published: 7271
        protocol: tcp
        mode: host
    env_file: .env
    command: mvn exec:java -Dexec.mainClass="coordinator.Coordinator" -Dexec.args="${S3_BUCKET} ${AWS_S3_ACCESS_KEY} ${AWS_S3_SECRET_KEY} ${REDIS_HOST} ${REDIS_PORT} ${REDIS_HOST_TIMES} ${REDIS_PORT_TIMES} ${WORKER_APP_PORT} ${COORDINATOR_APP_PORT} ${POSTGRES_PASSWORD} ${POSTGRES_USERNAME} ${POSTGRES_HOST} ${POSTGRES_PORT} ${POSTGRES_DB_NAME} ${MODE}"

    networks:
      cloud:
        aliases:
          - coordinator
  worker:
    image: kristalys/dbms-worker:1.2
    networks:
      cloud:
        aliases:
          - worker
    deploy:
      replicas: 5
      placement:
        max_replicas_per_node: 25
        # constraints:
        #   - "node.role==manager"
    depends_on:
      - coordinator
    env_file: .env
    command: mvn exec:java -Dexec.mainClass="orc.main" -Dexec.args="${S3_BUCKET} ${AWS_S3_ACCESS_KEY} ${AWS_S3_SECRET_KEY} ${REDIS_HOST} ${REDIS_PORT} ${REDIS_HOST_TIMES} ${REDIS_PORT_TIMES} ${WORKER_APP_PORT} ${COORDINATOR_APP_PORT} ${POSTGRES_PASSWORD} ${POSTGRES_USERNAME} ${POSTGRES_HOST} ${POSTGRES_PORT} ${POSTGRES_DB_NAME} ${MODE}"
networks:
  cloud:
    driver: overlay
    attachable: true
    driver_opts:
      com.docker.network.driver.mtu: 1442
#    external: true
