version: "3.9"
services:
  coordinator:
    image: coordinator
    container_name: coordinator
    ports:
      - target: 7271
        published: 7271
        protocol: tcp
        mode: host
    networks:
      cloud:
        aliases:
          - coordinator
  worker:
    image: worker
    networks:
      cloud:
        aliases:
          - worker
    deploy:
      replicas: 10
      placement:
        max_replicas_per_node: 10
    depends_on:
      - coordinator
    command: ./wait-for-it.sh 172.20.59.90:6379 -- mvn exec:java -Dexec.mainClass="orc.main"

networks:
  cloud:
    driver: overlay
    attachable: true
#    external: true