version: '3.9'
services:
  coordinator:
    image: kristalys/dbms-coordinator:2.5
    container_name: coordinator
    logging:
        driver: json-file
        options:
            max-size: "100m"
            max-file: "5"
    deploy:
      placement:
        constraints:
          - "node.role==manager"
    ports:
      - target: 7271
        published: 7271
        protocol: tcp
        mode: host
    env_file: .env
    networks:
      cloud:
        aliases:
          - coordinator
  worker-python:
    image: kristalys/dbms-worker-python:3.5
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "5"
    networks:
      cloud:
        aliases:
          - worker
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==worker"
          - "node.labels.processor==gpu"
    depends_on:
      - coordinator
    env_file: .env
  worker:
    image: kristalys/dbms-worker:2.5
    logging:
        driver: json-file
        options:
            max-size: "100m"
            max-file: "5"
    networks:
      cloud:
        aliases:
          - worker
    deploy:
      replicas: 60
      placement:
        max_replicas_per_node: 6
        constraints:
          - "node.role==worker"
          - "node.labels.type==memory"
    depends_on:
      - coordinator
    env_file: .env
networks:
  cloud:
    driver: overlay
    attachable: true
    driver_opts:
      com.docker.network.driver.mtu: 1442
#    external: true
