version: "3.9"
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      cloud:
        aliases:
          - redis
  server:
    build: /Coordinator
    image: server
    container_name: coordinator
    ports:
      - "7271:7271"
    networks:
      cloud:
        aliases:
          - server
    depends_on:
      - redis
  worker:
    build: /Distributed-DBMS
    image: worker
    networks:
      cloud:
        aliases:
          - worker
    deploy:
      replicas: 20
      placement:
        max_replicas_per_node: 5
    depends_on:
      - redis
      - coordinator
    command: ./wait-for-it.sh redis:6379 -- mvn exec:java -Dexec.mainClass="orc.main" -Dexec.args=$IP
networks:
  cloud:
    driver: overlay
    attachable: true
volumes:
  storage: